### ISSUE TITLE
Getting error app:validateSigningDebug.

### ISSUE THREAD

**Issue by CoderelTechnology** [invertase/react-native-firebase-starter#139]
I was using earlier starter that used RN 0.59. Now trying to install new starter I can rename project successfully but after that running the project gives me the error below.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file 'C:\Users\....\react-native-firebase-starter\android\app\debug.keystore' not found for signing config 'debug'.

**Comment by mikehardy** [comment]
This is an unfortunate upstream bug / developer experience issue that will be fixed in react-native 0.61. https://github.com/facebook/react-native/commit/d550256

The easiest way to resolve is to find *any* other debug.keystore on your filesystem (they are all the same really) and copy it in to the referenced path

Note that you may need to then update the SHA hash for your key in the firebase console for the given signing key

**Comment by mikehardy** [comment]
I pulled that change into the starter so future users don't hit that snag, it's frustrating
