### ISSUE TITLE
Do you guys need help migrating to rnf 6.0?

### ISSUE THREAD

**Issue by technoplato** [invertase/react-native-firebase-starter#141]

**Comment by technoplato** [comment]
I don’t think it seems too difficult but I’d love to start contributing a little more.

**Comment by mikehardy** [comment]
I think the starter app may disappear for RNFBv6 - but not because the use case and solution go away, just that the @react-native-community/cli has the ability to init more powerfully from templates now, and RNFB provides a v6 template for the CLI, so the invertase.io v6 docs starter path (which contain a CLI init with an RNFB v6 template) could be considered the starter app

Have you tried it?

**Comment by Salakar** [comment]
@mikehardy is correct, I'll update this repo to reflect that it's for v5 only. v6 should be through the template.

**Comment by technoplato** [comment]
Now that you mention the CLI init template methodology, I think I recall seeing that in the new project setup on the new site.

```
npx @react-native-community/cli init --template=@react-native-firebase/template <name>
```

Link to site for anyone that may (perhaps doubtfully) come across this: https://invertase.io/oss/react-native-firebase/quick-start/new-project

Thanks guys!
