### ISSUE TITLE
Build does not pass (Android)

### ISSUE THREAD

**Issue by Jakst** [invertase/react-native-firebase-starter#20]
Commit: d05061f129623bafb34cacf8e7f558b2be55ad22

Building the project version with `./gradlew build` does not work.

First time you try it you get the following error

```
react-native-firebase-starter/android/app/build/intermediates/res/merged/release/drawable-mdpi/assets_rnfirebase.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

FAILURE: Build failed with an exception.
```

This is a common react-native error, and is easily fixed by adding `android.enableAapt2=false` to gradle.properties.

Attempting to build again generates the following error: 
```
react-native-firebase-starter/android/app/build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.0.2, 26.1.0. Examples include com.android.support:animated-vector-drawable:27.0.2 and com.android.support:support-media-compat:26.1.0 [GradleCompatible]
```

This error can be solved by adding the following code to android/build.gradle:
```
allprojects {
    repositories {
        ....
        configurations.all {
            resolutionStrategy {
                force "com.android.support:appcompat-v7:27.0.2"
                force "com.android.support:support-v4:27.0.2"
            }
        }
    }
}
```

Running `./gradlew build` again results in a permission error that I cannot solve however:

```
  The first 3 errors (out of 8) were:
 react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:34: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
      FirebaseAnalytics.getInstance(getReactApplicationContext()).logEvent(name, Arguments.toBundle(params));
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:42: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
      FirebaseAnalytics.getInstance(getReactApplicationContext()).setAnalyticsCollectionEnabled(enabled);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 react-native-firebase-starter/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:58: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
            FirebaseAnalytics.getInstance(getReactApplicationContext()).setCurrentScreen(activity, screenName, screenClassOverride);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Salakar** [comment]
@Jakst try adding the permissions mentioned to your AndroidManifest file

**Comment by Jakst** [comment]
@Salakar Sorry if I wasn't clear. Adding the permissions in the manifest-file belonging to this project solves nothing.

**Comment by Salakar** [comment]
@Jakst could you show us your AndroidManifest file please, thanks

**Comment by hayatae** [comment]
I've got the exact same issue on my react-native project that I'm trying to add react-native-firebase to. I followed the same step for adding `android.enableAapt2=false` to my gradle.properties file, but instead of forcing v27 for the appcompat library, I just changed my app's build.gradle to use `compileSdkVersion 26` and set the appcompat-v7 library to 26.1.0.

What's really confusing me is that my project is *not* using firebase analytics at all. I'm not loading that module, so I don't know why the linter is trying to check permissions for it in the first place. Here's my console output from ./gradlew build:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-firebase:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  The first 3 errors (out of 9) were:
  /Users/mose/Projects/kemetical-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:34: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
      FirebaseAnalytics.getInstance(getReactApplicationContext()).logEvent(name, Arguments.toBundle(params));
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/mose/Projects/kemetical-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:42: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
      FirebaseAnalytics.getInstance(getReactApplicationContext()).setAnalyticsCollectionEnabled(enabled);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Users/mose/Projects/kemetical-app/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/analytics/RNFirebaseAnalytics.java:58: Error: Missing permissions required by FirebaseAnalytics.getInstance: android.permission.ACCESS_NETWORK_STATE and android.permission.WAKE_LOCK [MissingPermission]
            FirebaseAnalytics.getInstance(getReactApplicationContext()).setCurrentScreen(activity, screenName, screenClassOverride);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

And my permissions set in my AndroidManifest.xml:
`    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />`

**Comment by iooi** [comment]
Same here. Please fix!

**Comment by Salakar** [comment]
React Native Firebase v4.3.x support is now on master, which covers this - will close this issue now. Thanks for the feedback.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
